version: '3.5'
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
    ### Product Catalog service #############################################
    app:
      build: .
      volumes:
        - .:/app
      ports:
        - "${PRODUCT_SERVICE_PORT}:8080"
      networks:
        - backend