export const products = [
    {"id": 1, "name": "Chicken Fillets, 6 x 100g", "image_path": "product4.png", "category": "Meat & Poultry", "price": 4.50, "available": 12},
    {"id": 2, "name": "Sirloin Steaks, 4 x 6-8oz", "image_path": "product5.png", "category": "Meat & Poultry", "price": 45.70, "available": 6},
    {"id": 3, "name": "Whole Free-Range Turkey, 1 x 16-18lbs", "image_path": "product6.png", "category": "Meat & Poultry", "old_price": 48.25, "price": 43.20, "available": 8},
    {"id": 4, "name": "Granny Smith Apples, 4 x 16 each", "image_path": "product7.png", "category": "Fruit & Vegetables", "price": 3.75, "available": 0},
    {"id": 5, "name": "Loose Carrots, 4 x 20 each", "image_path": "product8.png", "category": "Fruit & Vegetables", "price": 2.67, "available": 2},
    {"id": 6, "name": "Mandarin Oranges, 6 x 10 x 12", "image_path": "product9.png", "category": "Fruit & Vegetables", "price": 12.23, "available": 8},
    {"id": 7, "name": "Cauliflower Florets, 10 x 500g", "image_path": "product10.png", "category": "Fruit & Vegetables", "old_price": 6.75, "price": 5.00, "available": 5},
    {"id": 8, "name": "Coca-Cola, 6 x 2L", "image_path": "product3.png", "category": "Drinks", "old_price": 8.50, "price": 8.30, "available": 6},
    {"id": 9, "name": "Still Mineral Water, 6 x 24 x 500ml", "image_path": "product1.png", "category": "Drinks", "price": 21.75, "available": 9},
    {"id": 10, "name": "Sparkling Mineral Water, 6 x 24 x 500ml", "image_path": "product2.png", "category": "Drinks", "price": 25.83, "available": 16},
    {"id": 11, "name": "Mars Bar, 6 x 24 x 50g", "image_path": "product11.png", "category": "Confectionary & Desserts", "price": 42.82, "available": 4},
    {"id": 12, "name": "Peppermint Chewing Gum, 6 x 50 x 30g", "image_path": "product12.png", "category": "Confectionary & Desserts", "price": 35.70, "available": 6},
    {"id": 13, "name": "Strawberry Cheesecake, 4 x 12 portions", "image_path": "product13.png", "category": "Confectionary & Desserts", "price": 8.52, "available": 0},
    {"id": 14, "name": "Vanilla Ice Cream, 6 x 4L", "image_path": "product14.png", "category": "Confectionary & Desserts", "price": 3.80, "available": 2},
    {"id": 15, "name": "Plain Flour, 10 x 1kg", "image_path": "product15.png", "category": "Baking/Cooking Ingredients", "price": 6.21, "available": 4},
    {"id": 16, "name": "Icing Sugar, 12 x 500g", "image_path": "product16.png", "category": "Baking/Cooking Ingredients", "price": 9.38, "available": 6},
    {"id": 17, "name": "Free-Range Eggs, 10 x 12 each", "image_path": "product17.png", "category": "Baking/Cooking Ingredients", "price": 9.52, "available": 9},
    {"id": 18, "name": "Caster Sugar, 16 x 750g", "image_path": "product18.png", "category": "Baking/Cooking Ingredients", "price": 12.76, "available": 13},
    {"id": 19, "name": "Kitchen Roll, 100 x 300 sheets", "image_path": "product19.png", "category": "Miscellaneous Items", "price": 43.92, "available": 19},
    {"id": 20, "name": "Paper Plates, 10 x 200 each", "image_path": "product20.png", "category": "Miscellaneous Items", "price": 16.19, "available": 7},
];